name: generate-docs
on:
  workflow_dispatch: {} # allow manually triggering the workflow
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml
      - "tools/**"
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for mkdocs gh-deploy to publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
